Master
rafaelpfreire/rubix pull request #1
Opened 2016-08-29 22:39 UTC by mauromascarenhas

Improvements implemented.

2016-10-15 11:58 UTC, rafaelpfreire commented on README.md
> +# RUBIX
Mauro, pode retirar esta linha? Minha ideia era tentar deixar multiplataforma.

2016-10-15 11:59 UTC, rafaelpfreire commented on README.md
> +#Aviso importante
Acho que esse é um aviso importante, mas pode deixá-lo em inglês?

2016-10-15 12:01 UTC, rafaelpfreire commented on README.md
> +#ATENÇÃO: Código Aberto | Licença de terceiros
Acho legal deixar esse parágrafo falando da licença, mas sem a parte de ser "clonado". E também em inglês, para ficar igual ao resto

2016-10-15 12:04 UTC, rafaelpfreire commented on frmabout.ui
> +     <string>Rubix Cube Game 3D! - Remastered</string>
Poderia deixar o nome como "Rubix Cube Game 3D!"? Acho que seria legal tirar o "Remastered". Verificar outras partes do código com o nome também.

2016-10-15 12:07 UTC, rafaelpfreire commented on mainwindow.ui
> +   <string>Rubix Cube Game 3D! - Remastered</string>
Aqui o Remastered também.

2016-10-15 12:18 UTC, rafaelpfreire requested changes
Mauro, primeiramente muito obrigado pela contribuição! Mas acho que valeria a pena fazermos algumas alterações antes de dar um merge no meu repositório. Deixei alguns comentários no código, o que vc acha?

2016-10-16 01:59 UTC, mauromascarenhas commented on README.md
> +#Aviso importante
Sim, se você observar o arquivo Readme original, notará que existem dois idiomas, o arquivo encontra-se totalmente em inglês após a tag EN.

2016-10-16 02:04 UTC, mauromascarenhas commented on README.md
> +#ATENÇÃO: Código Aberto | Licença de terceiros
Vou reverter as alterações no README para deixar igual ao seu, daí você dá o merge, e depois eu modifico de novo (isso se você preferir), quanto ao idioma em inglês, ele já está traduzido em dois idiomas.

2016-10-16 02:05 UTC, mauromascarenhas commented on frmabout.ui
> +     <string>Rubix Cube Game 3D! - Remastered</string>
Ok, se você preferir. Essa modificação será feira assim que possível.

2016-10-16 02:05 UTC, mauromascarenhas commented on mainwindow.ui
> +   <string>Rubix Cube Game 3D! - Remastered</string>
Ok, removerei.

2016-10-16 02:07 UTC, mauromascarenhas commented on README.md
> +# RUBIX
Esse for Windows é redundante, realmente ele é multiplataforma (Se você olhar o qmake notará que a inclusão da biblioteca será ignorada se não estiver sendo compilado no Win32). Essa linha pode ser retirada tranquilamente.

2016-10-16 02:08 UTC, mauromascarenhas commented
Ok, vamos verificar os pontos abordados. Estou aguardando as respostas.

2016-10-16 02:12 UTC, mauromascarenhas commented
Ok, assim que você der uma olhada nas respostas (e respondê-las de novo hehe), poderei efetuar as modificações.

2016-10-16 12:24 UTC, rafaelpfreire commented on README.md
> +# RUBIX
Humm, agora eu vi. Legal! Acho que podemos então descrever que ele é multiplataforma, ao invés de somente citar o Windows. Também nas seguintes variáveis no qmake, deixe o nome da sua empresa como contribuidora, mas coloque o meu também, por favor.

QMAKE_TARGET_COMPANY = Nintersoft
QMAKE_TARGET_PRODUCT = Rubix
QMAKE_TARGET_DESCRIPTION = Rubix Cube Game 3D! - Remastered
QMAKE_TARGET_COPYRIGHT = Copyright (c) 2016 Nintersoft

2016-10-16 12:25 UTC, rafaelpfreire commented on README.md
> +#Aviso importante
Ah sim, não tinha reparado. Vamos deixar assim então, ficou bom.

2016-10-16 12:28 UTC, rafaelpfreire commented on README.md
> +#ATENÇÃO: Código Aberto | Licença de terceiros
Ok, deixe nos 2 idiomas então, ficou bom. Acho que essa alteração é muito simples, talvez valha a pena fazer agora já. Assim já matamos isso. Você pode dar um push dessa alteração somente para este repositório, para manter o seu do jeito que está.

2016-10-16 12:29 UTC, rafaelpfreire commented
Pronto. Obrigado novamente, Mauro.

2016-10-20 17:47 UTC, mauromascarenhas commented on README.md
> +# RUBIX
Tudo bem, farei as mudanças requeridas.

2016-10-20 17:47 UTC, mauromascarenhas commented on README.md
> +#Aviso importante
Ok

2016-10-20 17:48 UTC, mauromascarenhas commented on README.md
> +#ATENÇÃO: Código Aberto | Licença de terceiros
Tudo bem, o farei.

2016-10-24 03:25 UTC, mauromascarenhas commented
Rafael, fiz algumas alterações.
Dá uma olhada pra ver o que você acha.
Qualquer coisa é só chamar.

2016-11-05 10:42 UTC, merged